CREATE DATABASE CL_SPORTS;

USE CL_SPORTS;

CREATE TABLE Item_Stock(
ItemNum VARCHAR(10) NOT NULL,
Category VARCHAR(10) NOT NULL,
Model VARCHAR(10) NOT NULL,
Size VARCHAR(10) NOT NULL,
Price VARCHAR(10) NOT NULL,
PRIMARY KEY (ItemNum) );

CREATE TABLE Purchase_Orders(
OrderNum VARCHAR(10) NOT NULL,
ItemNum VARCHAR(10) NOT NULL,
Price VARCHAR(10) NOT NULL,
PRIMARY KEY (OrderNum),
FOREIGN KEY (ItemNum) REFERENCES Item_Stock (ItemNum)
ON UPDATE CASCADE);

CREATE TABLE Date_Time(
Day VARCHAR(10) NOT NULL,
Month VARCHAR(10) NOT NULL,
Year VARCHAR(10) NOT NULL,
PRIMARY KEY  (YEAR) );

CREATE TABLE Location(
Address VARCHAR(10) NOT NULL,
Eircode VARCHAR(10) NOT NULL,
PRIMARY KEY (Address) );






